version: 0.2

phases:
  build:
    commands:
      # set environment variables
      - export IS_CODEBUILD_IMAGE="true"

      # run linters
      - TOX_PARALLEL_NO_SPINNER=1
      - tox -e flake8,black-check,pylint --parallel all

      # run README check
      - tox -e twine

      # run unit tests
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        tox -e py27,py36 -- test/unit

      # run functional tests
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - IGNORE_COVERAGE=- tox -e py27,py36 -- test/functional
